# fly.toml app configuration file generated for workout-tracker-and-generator on 2025-05-06T22:39:18Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'workout-tracker-and-generator'
primary_region = 'yul'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
